### PR TITLE
add proxy support

### PR DESCRIPTION
**Pull request by ghdiska**
Add alert ( global or specific) proxy settings

### CODE REVIEW

**Comment by ghdiska** [comment]
Some previewes
image
image

**Comment by ghdiska** [comment]
@ziegfried there are problems with my pr? i there's something i have to do i'm here

**Comment by ziegfried** [comment]
> @ziegfried there are problems with my pr? i there's something i have to do i'm here

Hi @ghdiska! Thanks for submitting your contribution! Also, thank you for signing the CLA! I haven't had a chance to take a detailed look yet, but from first glance I don't see any issues. I do want to test it before I release a new version, this may take me a couple of days before I get to it.

**Comment by ziegfried** [comment]
Included in 2.3.1 on splunkbase, thanks! Sorry this took so long 😬

**Pull request closed without merging**
